services:
  app_blue:
    image: yousxf/fastapi-app:ac2025c
    container_name: prod_app_blue
    profiles: ["blue"]
    ports: ["8080:8000"]
    restart: unless-stopped

  app_green:
    image: yousxf/fastapi-app:ac2025c
    container_name: prod_app_green
    profiles: ["green"]
    ports: ["8080:8000"]
    restart: unless-stopped